import { SeedProtocol } from "./types";

export const DEFAULT_SEED_PROTOCOLS: SeedProtocol[] = [
  {
    id: "rice",
    commonName: "Rice",
    scientificName: "Oryza sativa",
    family: "Poaceae",
    germinationDays: "~7 days germination",
    emoji: "🌾",
    description: "Cereal grain staple requiring precise anaerobic-to-aerobic moisture transition during radicle emergence.",
    referenceStandard: "IRRI / ISTA Standard Method 2021",
    riskFactors: ["Stagnant hypoxia", "Pythium blight if over-saturated above 32°C"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: Imbibition & Radicle Emergence",
        daysRange: "Days 0-2",
        tempRange: { min: 25, optimal: 30, max: 35 },
        humidityRange: { min: 75, optimal: 85, max: 92 },
        moistureTarget: "75-85% Index",
        lightRegime: "Darkness (promotes coleoptile initiation)",
        ventilationSchedule: "Micro-ventilation 15° every 6 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 240,
          pumpDurationSeconds: 8,
          fanDutyCycle: 0,
          ventAngleDegrees: 15,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Coleoptile Elongation",
        daysRange: "Days 3-5",
        tempRange: { min: 24, optimal: 28, max: 32 },
        humidityRange: { min: 70, optimal: 80, max: 88 },
        moistureTarget: "70-78% Index",
        lightRegime: "Diffuse ambient light (10h/day)",
        ventilationSchedule: "Active purge 35° every 3 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 6,
          fanDutyCycle: 50,
          ventAngleDegrees: 35,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: First Foliar Leaf Expansion",
        daysRange: "Days 6-7",
        tempRange: { min: 22, optimal: 26, max: 30 },
        humidityRange: { min: 65, optimal: 75, max: 85 },
        moistureTarget: "65-72% Index",
        lightRegime: "High intensity canopy light (12h/day)",
        ventilationSchedule: "Continuous low airflow (45° vent)",
        deterministicActuation: {
          pumpIntervalMinutes: 120,
          pumpDurationSeconds: 5,
          fanDutyCycle: 70,
          ventAngleDegrees: 45,
        },
      },
    ],
  },
  {
    id: "wheat",
    commonName: "Wheat",
    scientificName: "Triticum aestivum",
    family: "Poaceae",
    germinationDays: "~7 days germination",
    emoji: "🌾",
    description: "Temperate hexaploid monocot sensitive to high thermal sums during primary seminal root initiation.",
    referenceStandard: "FAO Plant Production Paper 145",
    riskFactors: ["Fusarium crown rot if humidity exceeds 90%", "Thermal dormancy above 28°C"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: Seminal Root Initiation",
        daysRange: "Days 0-2",
        tempRange: { min: 15, optimal: 20, max: 25 },
        humidityRange: { min: 70, optimal: 80, max: 88 },
        moistureTarget: "68-75% Index",
        lightRegime: "Complete darkness",
        ventilationSchedule: "Passive airflow",
        deterministicActuation: {
          pumpIntervalMinutes: 300,
          pumpDurationSeconds: 6,
          fanDutyCycle: 0,
          ventAngleDegrees: 20,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Coleoptile Breach & Emergence",
        daysRange: "Days 3-5",
        tempRange: { min: 16, optimal: 21, max: 24 },
        humidityRange: { min: 65, optimal: 75, max: 82 },
        moistureTarget: "65-72% Index",
        lightRegime: "Diffuse canopy light (12h/day)",
        ventilationSchedule: "Micro-vent purge 30° every 4 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 240,
          pumpDurationSeconds: 5,
          fanDutyCycle: 40,
          ventAngleDegrees: 30,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: Primary Leaf Photosynthetic Transition",
        daysRange: "Days 6-7",
        tempRange: { min: 18, optimal: 22, max: 25 },
        humidityRange: { min: 60, optimal: 70, max: 80 },
        moistureTarget: "60-68% Index",
        lightRegime: "Direct spectrum (14h/day)",
        ventilationSchedule: "Active circulation 45°",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 5,
          fanDutyCycle: 60,
          ventAngleDegrees: 45,
        },
      },
    ],
  },
  {
    id: "maize",
    commonName: "Maize",
    scientificName: "Zea mays",
    family: "Poaceae",
    germinationDays: "~10 days germination",
    emoji: "🌽",
    description: "C4 high-efficiency crop with large endosperm reserves requiring consistent aerobic warmth.",
    referenceStandard: "CIMMYT Seed Health Manual 2020",
    riskFactors: ["Cold-shock imbibition damage below 12°C", "Pythium ultimum damping-off"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: Primary Imbibition & Warm Activation",
        daysRange: "Days 0-3",
        tempRange: { min: 20, optimal: 27, max: 32 },
        humidityRange: { min: 72, optimal: 82, max: 90 },
        moistureTarget: "72-80% Index",
        lightRegime: "Darkness",
        ventilationSchedule: "Sealed chamber, gentle purge",
        deterministicActuation: {
          pumpIntervalMinutes: 240,
          pumpDurationSeconds: 8,
          fanDutyCycle: 0,
          ventAngleDegrees: 15,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Mesocotyl & Coleoptile Penetration",
        daysRange: "Days 4-7",
        tempRange: { min: 22, optimal: 28, max: 32 },
        humidityRange: { min: 68, optimal: 78, max: 85 },
        moistureTarget: "68-75% Index",
        lightRegime: "Gradual photoperiod introduction",
        ventilationSchedule: "Micro-ventilation 35° every 3 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 7,
          fanDutyCycle: 50,
          ventAngleDegrees: 35,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: V1 Leaf Collar Unfurling",
        daysRange: "Days 8-10",
        tempRange: { min: 22, optimal: 26, max: 30 },
        humidityRange: { min: 60, optimal: 72, max: 80 },
        moistureTarget: "65-72% Index",
        lightRegime: "Full growth spectrum (14h/day)",
        ventilationSchedule: "Continuous air renewal 50°",
        deterministicActuation: {
          pumpIntervalMinutes: 120,
          pumpDurationSeconds: 6,
          fanDutyCycle: 65,
          ventAngleDegrees: 50,
        },
      },
    ],
  },
  {
    id: "tomato",
    commonName: "Tomato",
    scientificName: "Solanum lycopersicum",
    family: "Solanaceae",
    germinationDays: "~14 days germination",
    emoji: "🍅",
    description: "High-value horticultural dicot with epigeal germination; sensitive to moisture fluctuations.",
    referenceStandard: "ISTA Rules for Seed Testing, Solanaceous Dicot",
    riskFactors: ["Hypocotyl rot", "High ambient RH fungal bloom >88%"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: Radicle Emergence & Testa Rupture",
        daysRange: "Days 0-4",
        tempRange: { min: 20, optimal: 25, max: 30 },
        humidityRange: { min: 70, optimal: 80, max: 88 },
        moistureTarget: "70-76% Index",
        lightRegime: "Darkness ensures uniform radicle growth",
        ventilationSchedule: "Micro-vent 20° every 4 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 240,
          pumpDurationSeconds: 6,
          fanDutyCycle: 20,
          ventAngleDegrees: 20,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Hypocotyl Arch Emergence",
        daysRange: "Days 5-9",
        tempRange: { min: 21, optimal: 24, max: 28 },
        humidityRange: { min: 65, optimal: 75, max: 82 },
        moistureTarget: "65-72% Index",
        lightRegime: "50% diffuse canopy light",
        ventilationSchedule: "Regulated venting 40°",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 5,
          fanDutyCycle: 45,
          ventAngleDegrees: 40,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: Cotyledon Opening & True Leaf Primordia",
        daysRange: "Days 10-14",
        tempRange: { min: 20, optimal: 23, max: 26 },
        humidityRange: { min: 60, optimal: 70, max: 78 },
        moistureTarget: "62-70% Index",
        lightRegime: "Full photosynthetic spectrum (14h/day)",
        ventilationSchedule: "Active continuous circulation 60°",
        deterministicActuation: {
          pumpIntervalMinutes: 150,
          pumpDurationSeconds: 5,
          fanDutyCycle: 60,
          ventAngleDegrees: 60,
        },
      },
    ],
  },
  {
    id: "ragi",
    commonName: "Ragi",
    scientificName: "Eleusine coracana",
    family: "Poaceae (Finger Millet)",
    germinationDays: "~10 days germination",
    emoji: "🌱",
    description: "Resilient small millet with rapid metabolic activation; high calcium content and drought adaptation.",
    referenceStandard: "ICRISAT Small Millets Protocol",
    riskFactors: ["Over-irrigation in shallow soil", "Stagnant substrate crusting"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: Rapid Seed Swelling & Priming",
        daysRange: "Days 0-2",
        tempRange: { min: 22, optimal: 28, max: 33 },
        humidityRange: { min: 65, optimal: 75, max: 85 },
        moistureTarget: "68-75% Index",
        lightRegime: "Darkness",
        ventilationSchedule: "Periodic purge 20°",
        deterministicActuation: {
          pumpIntervalMinutes: 300,
          pumpDurationSeconds: 5,
          fanDutyCycle: 0,
          ventAngleDegrees: 20,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Shoot & Adventitious Root Initiation",
        daysRange: "Days 3-6",
        tempRange: { min: 24, optimal: 29, max: 34 },
        humidityRange: { min: 62, optimal: 72, max: 80 },
        moistureTarget: "62-70% Index",
        lightRegime: "Moderate daylight (12h/day)",
        ventilationSchedule: "Vent 35° every 4 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 240,
          pumpDurationSeconds: 5,
          fanDutyCycle: 40,
          ventAngleDegrees: 35,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: Crown Root Anchorage & Tillering Preparation",
        daysRange: "Days 7-10",
        tempRange: { min: 23, optimal: 27, max: 32 },
        humidityRange: { min: 58, optimal: 68, max: 78 },
        moistureTarget: "60-66% Index",
        lightRegime: "Full sunlight simulation (13h/day)",
        ventilationSchedule: "Continuous ventilation 45°",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 4,
          fanDutyCycle: 55,
          ventAngleDegrees: 45,
        },
      },
    ],
  },
  {
    id: "moong-bean",
    commonName: "Moong Bean",
    scientificName: "Vigna radiata",
    family: "Fabaceae (Green Gram)",
    germinationDays: "~3 days germination",
    emoji: "🌱",
    description: "Rapidly germinating legume with active hypogeal/epigeal transition; high protein reserve mobilization.",
    referenceStandard: "AVRDC World Vegetable Center Guideline",
    riskFactors: ["Bacterial soft rot under excess moisture", "Anoxia in heavy substrate"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: High-Speed Imbibition",
        daysRange: "Day 0-1",
        tempRange: { min: 25, optimal: 30, max: 35 },
        humidityRange: { min: 75, optimal: 85, max: 92 },
        moistureTarget: "75-82% Index",
        lightRegime: "Complete darkness",
        ventilationSchedule: "Brief purges to maintain oxygen",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 7,
          fanDutyCycle: 20,
          ventAngleDegrees: 25,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Hypocotyl Extension",
        daysRange: "Day 2",
        tempRange: { min: 24, optimal: 28, max: 32 },
        humidityRange: { min: 70, optimal: 80, max: 88 },
        moistureTarget: "70-76% Index",
        lightRegime: "Low intensity diffuse light",
        ventilationSchedule: "Micro-ventilation 40° every 2 hours",
        deterministicActuation: {
          pumpIntervalMinutes: 150,
          pumpDurationSeconds: 5,
          fanDutyCycle: 40,
          ventAngleDegrees: 40,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: Fully Emerged Seedling",
        daysRange: "Day 3",
        tempRange: { min: 22, optimal: 26, max: 30 },
        humidityRange: { min: 65, optimal: 75, max: 82 },
        moistureTarget: "65-72% Index",
        lightRegime: "Full spectrum illumination (12h/day)",
        ventilationSchedule: "Continuous ventilation 50°",
        deterministicActuation: {
          pumpIntervalMinutes: 120,
          pumpDurationSeconds: 5,
          fanDutyCycle: 60,
          ventAngleDegrees: 50,
        },
      },
    ],
  },
];

/**
 * Creates a dynamic AI protocol for any custom seed entered by the user
 */
export function generateCustomProtocol(name: string): SeedProtocol {
  const cleanName = name.trim();
  const id = cleanName.toLowerCase().replace(/[^a-z0-9]/g, "-");
  return {
    id,
    commonName: cleanName,
    scientificName: `${cleanName} sp. (Botanical Calibration)`,
    family: "Agronomic Cultivar",
    germinationDays: "~7 days germination",
    emoji: "🌱",
    description: `AI-synthesized 3-epoch agronomy experiment protocol for ${cleanName} grounded in physiological seed science.`,
    referenceStandard: "Chiguru AI Agronomy Engine v2.0",
    riskFactors: ["Substrate saturation", "Thermal stress"],
    epochs: [
      {
        epochNumber: 1,
        name: "Epoch 1: Imbibition & Cellular Hydration",
        daysRange: "Days 0-2",
        tempRange: { min: 20, optimal: 25, max: 30 },
        humidityRange: { min: 70, optimal: 80, max: 88 },
        moistureTarget: "70-78% Index",
        lightRegime: "Darkness accelerates radicle elongation",
        ventilationSchedule: "Periodic micro-purge 20°",
        deterministicActuation: {
          pumpIntervalMinutes: 240,
          pumpDurationSeconds: 6,
          fanDutyCycle: 0,
          ventAngleDegrees: 20,
        },
      },
      {
        epochNumber: 2,
        name: "Epoch 2: Hypocotyl Penetration & Emergence",
        daysRange: "Days 3-5",
        tempRange: { min: 21, optimal: 24, max: 28 },
        humidityRange: { min: 65, optimal: 75, max: 82 },
        moistureTarget: "65-72% Index",
        lightRegime: "Diffuse spectrum (10h/day)",
        ventilationSchedule: "Regulated ventilation 35°",
        deterministicActuation: {
          pumpIntervalMinutes: 180,
          pumpDurationSeconds: 5,
          fanDutyCycle: 40,
          ventAngleDegrees: 35,
        },
      },
      {
        epochNumber: 3,
        name: "Epoch 3: Foliar Primordia & Autotrophic Shift",
        daysRange: "Days 6-7",
        tempRange: { min: 20, optimal: 23, max: 26 },
        humidityRange: { min: 60, optimal: 70, max: 78 },
        moistureTarget: "60-68% Index",
        lightRegime: "Full growth illumination (14h/day)",
        ventilationSchedule: "Active circulation 50°",
        deterministicActuation: {
          pumpIntervalMinutes: 150,
          pumpDurationSeconds: 5,
          fanDutyCycle: 60,
          ventAngleDegrees: 50,
        },
      },
    ],
  };
}
